import json
from datetime import datetime
from pathlib import Path
from rich.panel import Panel
from rich.rule import Rule
from opsec_guard.utils.display import console, risk_badge, score_to_level
from opsec_guard.utils.storage import load_latest_audit, list_audits


def _md_report(audit: dict) -> str:
    score   = audit["score"]
    level   = audit["level"]
    ts      = audit["timestamp"]
    answers = audit["answers"]
    sensitive = audit.get("sensitive_role", False)

    lines = [
        "# MAID Exposure Risk Report",
        f"> Generated by **opsec-guard** on {ts}",
        "",
        "---",
        "",
        "## Risk Summary",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Exposure Score | **{score}/100** |",
        f"| Risk Level | **{level.upper()}** |",
        f"| Sensitive Role | {'YES — elevated risk' if sensitive else 'No'} |",
        f"| Audit Date | {ts} |",
        "",
    ]

    lines += [
        "---",
        "",
        "## What is a MAID?",
        "",
        "A **Mobile Advertising ID (MAID)** is a unique resettable identifier embedded in every smartphone:",
        "- **Android**: GAID (Google Advertising ID)",
        "- **iOS**: IDFA (Identifier for Advertisers)",
        "",
        "MAIDs are read by advertising SDKs embedded in apps and combined with precise GPS coordinates.",
        "This data is transmitted to data brokers who sell movement profiles to advertisers, hedge funds,",
        "law enforcement, and intelligence agencies — often without meaningful user consent.",
        "",
    ]

    lines += [
        "---",
        "",
        "## Audit Responses",
        "",
        "| Question | Your Answer | Score Contribution |",
        "|----------|-------------|-------------------|",
    ]

    from opsec_guard.commands.audit import QUESTIONS
    for q in QUESTIONS:
        key = q["key"]
        a = answers.get(key, {})
        label = a.get("answer_label", "N/A")
        contrib = a.get("score_contribution", 0)
        lines.append(f"| {q['prompt']} | {label} | +{contrib} |")

    lines += [
        "",
        "---",
        "",
        "## Key Risk Findings",
        "",
    ]

    findings = _generate_findings(answers, sensitive)
    if findings:
        for f in findings:
            lines.append(f"- {f}")
    else:
        lines.append("- No critical findings. Maintain current practices.")

    lines += [
        "",
        "---",
        "",
        "## Recommendations",
        "",
    ]

    recs = _generate_recommendations(answers, sensitive)
    for i, (title, body) in enumerate(recs, 1):
        lines.append(f"### {i}. {title}")
        lines.append(f"{body}")
        lines.append("")

    lines += [
        "---",
        "",
        "## MAID Reset Instructions",
        "",
        "### Android",
        "1. Settings → Google → Ads → **Reset advertising ID**",
        "2. Android 12+: **Delete advertising ID** entirely",
        "3. Settings → Location → Wi-Fi scanning → **OFF**",
        "4. Settings → Location → Bluetooth scanning → **OFF**",
        "5. Review each app's location permission — change 'Always' to 'While Using' or 'Deny'",
        "",
        "### iOS",
        "1. Settings → Privacy & Security → Tracking → **Allow Apps to Request to Track → OFF**",
        "2. Settings → Privacy & Security → Apple Advertising → **Reset Advertising Identifier**",
        "3. Settings → Privacy & Security → Apple Advertising → **Personalized Ads → OFF**",
        "4. Settings → Privacy & Security → Location Services → disable **Precise Location** per app",
        "5. Settings → Privacy & Security → Location Services → System Services → **Significant Locations → OFF**",
        "",
        "---",
        "",
        "## Known High-Risk Apps (by Category)",
        "",
        "| App | Risk | Concern |",
        "|-----|------|---------|",
        "| The Weather Channel | HIGH | MAID+GPS sold to Cuebiq, IBM Watson |",
        "| AccuWeather | HIGH | GPS transmitted even when location disabled |",
        "| GasBuddy | HIGH | 14,000+ location pings/day per device |",
        "| Life360 | CRITICAL | 31M users' MAID+GPS sold to 3 brokers |",
        "| Muslim Pro | CRITICAL | MAID data sold to US military contractors |",
        "| Strava | HIGH | Exposed military/intel facility locations via heatmap |",
        "| Grindr | CRITICAL | MAID+HIV status sold to advertisers |",
        "| TikTok | HIGH | Device fingerprinting; ByteDance data access |",
        "",
        "---",
        "",
        "## Known MAID Data Brokers",
        "",
        "| Broker | Risk | Known Clients |",
        "|--------|------|---------------|",
        "| Babel Street (Locate X) | CRITICAL | Secret Service, law enforcement |",
        "| Venntel | CRITICAL | DHS, ICE, CBP, FBI, DEA |",
        "| X-Mode / Outlogic | CRITICAL | US military contractors |",
        "| SafeGraph | CRITICAL | CDC, government agencies, hedge funds |",
        "| Cuebiq | HIGH | Hedge funds, advertisers |",
        "| Kochava | CRITICAL | Law enforcement, advertisers |",
        "",
        "---",
        "",
        "## Legal Context",
        "",
        "Data collection via MAIDs requires **free, specific, and informed consent** under:",
        "- **GDPR** (EU) — Articles 6 and 7",
        "- **CCPA/CPRA** (California) — right to opt out of data sale",
        "- **Children's Online Privacy Protection Act (COPPA)** — apps used by minors",
        "",
        "In practice, consent is often obscured in lengthy privacy policies, and the broker",
        "ecosystem involves so many intermediaries that enforcement is difficult.",
        "",
        "---",
        "",
        "*This report was generated by [opsec-guard](https://github.com/arctracerexequias/opsec-guard).",
        "Data is based on public investigative journalism, regulatory complaints, and security research.*",
    ]

    return "\n".join(lines)


def _generate_findings(answers: dict, sensitive: bool) -> list[str]:
    findings = []

    if answers.get("maid_reset_frequency", {}).get("answer_index", 0) <= 1:
        findings.append("MAID has never or rarely been reset — persistent tracking profile likely exists in broker databases.")

    if answers.get("ad_tracking_opt_out", {}).get("answer_index", 0) == 0:
        findings.append("Ad tracking opt-out is not enabled — MAID is actively shared with advertising SDKs.")

    if answers.get("weather_apps", {}).get("answer_index", 3) == 0:
        findings.append("Weather app with background location access detected — primary MAID+GPS harvesting vector.")

    if answers.get("background_location", {}).get("answer_index", 3) <= 1:
        findings.append("Multiple apps have 'Always On' location access — continuous MAID+GPS transmission likely.")

    if answers.get("free_vpn", {}).get("answer_index", 1) == 0:
        findings.append("Free VPN app in use — commonly monetized via location data brokerage.")

    if sensitive and answers.get("work_personal_same_device", {}).get("answer_index", 1) == 0:
        findings.append("CRITICAL: Sensitive professional role + single device = direct OPSEC risk via MAID tracking.")

    return findings


def _generate_recommendations(answers: dict, sensitive: bool) -> list[tuple[str, str]]:
    recs = []

    if answers.get("maid_reset_frequency", {}).get("answer_index", 0) <= 2:
        recs.append(("Reset your MAID immediately and set a monthly reminder",
                     "Run `opsec-guard maid reset` for platform-specific steps. "
                     "On Android 12+, delete the GAID entirely."))

    if answers.get("ad_tracking_opt_out", {}).get("answer_index", 0) == 0:
        recs.append(("Enable system-wide ad tracking opt-out",
                     "Android: Settings → Google → Ads → Opt out of Ads Personalization. "
                     "iOS: Settings → Privacy → Tracking → disable 'Allow Apps to Request to Track'."))

    if answers.get("background_location", {}).get("answer_index", 3) <= 2:
        recs.append(("Audit and revoke background location permissions",
                     "No app should have 'Always On' location unless strictly necessary (e.g. navigation). "
                     "Change weather, social, and game apps to 'While Using' or 'Deny'."))

    if answers.get("free_vpn", {}).get("answer_index", 1) == 0:
        recs.append(("Replace free VPN with a paid, audited alternative",
                     "Recommended: Mullvad (no-logs, RAM-only servers) or ProtonVPN. "
                     "Free VPNs frequently monetize through selling user data to brokers."))

    if answers.get("wifi_scanning", {}).get("answer_index", 2) == 0:
        recs.append(("Disable Wi-Fi and Bluetooth scanning",
                     "Android: Settings → Location → Wi-Fi scanning → OFF, Bluetooth scanning → OFF. "
                     "These allow location inference even when GPS is disabled."))

    if sensitive:
        recs.append(("Implement device separation for sensitive roles",
                     "Use a dedicated work device with no advertising apps, managed via MDM. "
                     "Personal apps with embedded ad SDKs should never be installed on devices "
                     "used for sensitive operations."))

    recs.append(("Submit opt-out requests to known data brokers",
                 "Visit opt-out pages for: Cuebiq, SafeGraph, Veraset, Kochava, Acxiom, and LexisNexis. "
                 "Services like Incogni or DeleteMe can automate broker opt-out requests."))

    return recs


def run_report(output: str, fmt: str) -> None:
    console.print()
    audit = load_latest_audit()

    if audit is None:
        console.print(Panel(
            "[yellow]No saved audit found.[/yellow]\n\n"
            "Run [bold cyan]opsec-guard maid audit --save[/bold cyan] first to create an audit record.",
            border_style="yellow"
        ))
        return

    audits = list_audits()
    console.print(f"[dim]Using most recent audit: {audits[0].name}[/dim]")
    console.print(f"[dim]Score: {audit['score']}/100  Level: {audit['level'].upper()}[/dim]")
    console.print()

    if fmt == "markdown":
        content = _md_report(audit)
        Path(output).write_text(content)
        console.print(f"[green]Report saved to:[/green] [bold]{output}[/bold]")
    else:
        _text_report(audit)

    console.print()


def _text_report(audit: dict) -> None:
    console.print(Rule("[bold]MAID Exposure Report[/bold]"))
    console.print()
    console.print(f"  Score     : [bold]{audit['score']}/100[/bold]  {risk_badge(audit['level'])}")
    console.print(f"  Timestamp : {audit['timestamp']}")
    console.print(f"  Role      : {'[red]Sensitive[/red]' if audit.get('sensitive_role') else 'Standard'}")
    console.print()

    findings = _generate_findings(audit["answers"], audit.get("sensitive_role", False))
    if findings:
        console.print(Rule("[bold]Findings[/bold]"))
        for f in findings:
            console.print(f"  [red]•[/red] {f}")
        console.print()

    recs = _generate_recommendations(audit["answers"], audit.get("sensitive_role", False))
    console.print(Rule("[bold]Recommendations[/bold]"))
    for title, body in recs:
        console.print(f"  [bold cyan]{title}[/bold cyan]")
        console.print(f"  [dim]{body}[/dim]")
        console.print()
