"""Email alert system with executive escalation support."""
import smtplib
import json
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from pathlib import Path
from datetime import datetime, timezone

ALERTS_CONFIG_FILE = Path.home() / ".opsec-guard" / "alerts.json"
CONFIG_PATH = ALERTS_CONFIG_FILE  # alias for old code


def load_alert_config() -> dict:
    if not ALERTS_CONFIG_FILE.exists():
        return {}
    try:
        return json.loads(ALERTS_CONFIG_FILE.read_text())
    except Exception:
        return {}


# Alias for old code
load_config = load_alert_config


def save_alert_config(config: dict) -> None:
    ALERTS_CONFIG_FILE.parent.mkdir(mode=0o700, exist_ok=True)
    ALERTS_CONFIG_FILE.write_text(json.dumps(config, indent=2))
    ALERTS_CONFIG_FILE.chmod(0o600)


save_config = save_alert_config


def send_alert(
    subject: str,
    body: str,
    recipient: str,
    cc: list[str] | None = None,
    priority: str = "normal",
) -> tuple[bool, str]:
    config = load_alert_config()
    if not config:
        return False, "Alert system not configured. Run: opsec-guard alerts setup"

    smtp_host = config.get("smtp_host", "")
    smtp_port = int(config.get("smtp_port", 587))
    smtp_user = config.get("smtp_user", "")
    smtp_pass = config.get("smtp_pass") or config.get("smtp_password", "")
    from_addr = config.get("from_addr") or config.get("sender_email", smtp_user)

    if not all([smtp_host, smtp_user, smtp_pass]):
        return False, "Incomplete SMTP configuration."

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"[OPSEC-GUARD] {subject}"
    msg["From"] = f"OpsecGuard Security <{from_addr}>"
    msg["To"] = recipient
    if cc:
        msg["Cc"] = ", ".join(cc)
    if priority == "high":
        msg["X-Priority"] = "1"
        msg["X-MSMail-Priority"] = "High"

    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    html_body = f"""
<html><body style="font-family: Arial, sans-serif; color: #333;">
<div style="border-left: 4px solid {'#dc3545' if priority == 'high' else '#ffc107'}; padding: 12px 20px; margin: 10px 0;">
<h2 style="color: {'#dc3545' if priority == 'high' else '#e67e22'};">
  {'🚨 URGENT: ' if priority == 'high' else '⚠️ '}{subject}
</h2>
<pre style="background:#f8f9fa; padding:12px; border-radius:4px; white-space:pre-wrap;">{body}</pre>
<hr/>
<small style="color:#888;">Generated by OpsecGuard v2.0 · {timestamp}<br/>
This alert was sent to a registered protected personnel. Do not forward.</small>
</div>
</body></html>
"""
    msg.attach(MIMEText(html_body, "html"))

    try:
        with smtplib.SMTP(smtp_host, smtp_port, timeout=10) as server:
            server.ehlo()
            server.starttls()
            server.login(smtp_user, smtp_pass)
            all_recipients = [recipient] + (cc or [])
            server.sendmail(from_addr, all_recipients, msg.as_string())
        return True, f"Alert sent to {recipient}"
    except smtplib.SMTPAuthenticationError:
        return False, "SMTP authentication failed. Check credentials."
    except smtplib.SMTPConnectError:
        return False, f"Cannot connect to SMTP server {smtp_host}:{smtp_port}"
    except Exception as e:
        return False, f"Email error: {e}"


def send_executive_alert(person: dict, subject: str, body: str) -> list[tuple[bool, str]]:
    """Send alert to executive and their designated security officer."""
    results = []
    email = person.get("email")
    security_officer = person.get("security_officer_email")
    tier = person.get("tier", "standard")

    if email:
        priority = "high" if tier == "executive" else "normal"
        result = send_alert(subject, body, email, priority=priority)
        results.append(result)

    if security_officer and tier == "executive":
        officer_body = f"[Security Officer Alert]\nPersonnel: {person.get('name', 'Unknown')}\n\n{body}"
        result = send_alert(
            f"Executive Alert — {person.get('name', 'Unknown')}: {subject}",
            officer_body,
            security_officer,
            priority="high",
        )
        results.append(result)

    return results


def send_critical_alert(findings: list[str], score: int, level: str) -> tuple[bool, str]:
    """Legacy alias for old code compatibility."""
    if level not in ("critical", "high"):
        return False, "Alert not sent — risk level is not critical or high."
    subject = f"{level.upper()} MAID Exposure Alert — Score {score}/100"
    body = f"Risk Level: {level.upper()}\nScore: {score}/100\n\nFindings:\n" + "\n".join(f"- {f}" for f in findings)
    cfg = load_alert_config()
    recipient = cfg.get("recipient_email", "")
    if not recipient:
        return False, "No recipient configured."
    return send_alert(subject, body, recipient, priority="high" if level == "critical" else "normal")
